---

- name: Add Git branch to Bash prompt
  blockinfile:
    path: '$HOME/.bashrc'
    block: |
      # Git
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
      }
      
      export PS1="\u@\h \[\033[32m\]\w\[\033[1;31m\]\$(parse_git_branch)\[\033[00m\]\n$ "
    state: present
    validate: 'bash -n %s'
