---
- hosts: cloudlab
  become: no

  tasks:
    - name: Print OS and distro Ansible variables collected by setup
      debug:
        msg:
          - "ansible_os_family: {{ ansible_os_family }}"
          - "ansible_distribution: {{ ansible_distribution }}"
          - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
          - "ansible_distribution_version: {{ ansible_distribution_version }}"
          - "ansible_distribution_release: {{ ansible_distribution_release }}"

    - name: Update apt-get repo/cache
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install packages
      become: yes
      apt:
        name:
          - ca-certificates
          - curl
          - git
          - gnupg
          - htop
          - lsb-release
          - podman
          - python3
          - python3-pip
          - vim
        state: present

    - name: Install Pip packages
      become: yes
      pip:
        name:
          - podman-compose
          - python-dotenv
          - pyyaml

    - name: Git Config
      include_tasks: "tasks/gitconfig.yml"

    - name: Checking if repo already checked out
      stat:
        path: '$HOME/checkout'
      register: repo_checkout_path

    - name: Check out the GitHub repository
      when: not repo_checkout_path.stat.exists
      git:
        repo: "{{ github_repo_url }}"
        dest: "$HOME/checkout"
        depth: 0
        version: "{{ github_branch }}"
        force: yes
        update: yes

    - name: Check if CLion Remote container present
      shell: podman container exists clionremote
      register: clionremote_container_exists
      failed_when: no
      changed_when: no

    - name: Stop CLion Remote Container
      when: clionremote_container_exists.rc == 0
      shell: |
        podman stop clionremote
        podman rm clionremote
      tags:
        - remove-container

    - name: Run CLion Remote Container
      shell: |
        podman run -d \
          --cap-add sys_ptrace \
          -p127.0.0.1:2222:22 \
          -p127.0.0.1:18080:18080 \
          --name clionremote \
          {{ clionremote_image.name }}:{{ clionremote_image.tag }}
      tags:
        - run-container
